BEGIN TRANSACTION;

PRAGMA forreign_keys=true;

CREATE TABLE IF NOT EXISTS TBL_SPECIAL_WEAPON (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TBL_SUB_WEAPON (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TBL_WEAPON_TYPE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TBL_WEAPON (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE,
    typeId INTEGER NOT NULL,
    subId INTEGER NOT NULL,
    specialId INTEGER NOT NULL,
    FOREIGN KEY (subId) REFERENCES TBL_SUB_WEAPON(id),
    FOREIGN KEY (specialId) REFERENCES TBL_SPECIAL_WEAPON(id),
    FOREIGN KEY (typeId) REFERENCES TBL_WEAPON_TYPE(id)
);

CREATE TABLE IF NOT EXISTS TBL_STAGE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS TBL_RULE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rule TEXT UNIQUE
);

--検討中--
CREATE TABLE IF NOT EXISTS TBL_GUILD (
    id INTEGER PRIMARY KEY,
    name TEXT
);

--検討中--
CREATE TABLE IF NOT EXISTS TBL_PLAYER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    guildId INTEGER,
    name TEXT
);

--検討中--
CREATE TABLE IF NOT EXISTS TBL_FORMATION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    playerId INTEGER,
    weaponId INTEGER
);

COMMIT TRANSACTION;
